### ISSUE TITLE
Directory tasks

### ISSUE THREAD

**Issue by adamralph** [adamralph/bau#172]

**Comment by aarondandy** [comment]
Would this include things such as copying entire directories or would that be something else? Would you prefer to have a C# based directory copy task or would that be best left to a call to a copy command through the Exec task?

**Comment by aarondandy** [comment]
Duplicate of #186 ?

**Comment by adamralph** [comment]
Well spotted ;-).

I imagine other stuff like copying directories would be covered by #187. The most common operations, (e.g. creating a directory) are candidates for being wrapped in tasks.
