### ISSUE TITLE
Prerequisites / cross platform compatibility

### ISSUE THREAD

**Issue by keichinger** [adamralph/bau#183]
Hey,

when trying to install bau (or rather scriptcs) on an Linux or OSX machine you'll most likely run into some compatibility issues because some system packages are simply missing.

Let's say I'm executing bau.sh on my OSX 10.10 machine it'll error out because:
- `wget` is not pre-installed on OSX
- `unzip` is not pre-installed on OSX

While it's rather safe to assume that `wget` is installed on Linux it is much safer to use `curl` to download the scriptcs NuGet package.

So line 17 of `bau.sh` should look like this:

``` bash
curl -O "https://github.com/bau-build/bau-blob/raw/master/scriptcs-0.10.0-alpha.140530.nupkg"
```

This is one problem fixed. The next problem is a bit more tricky as _unzip_ isn't pre-installed on any popular distribution as far as I'm aware of. One simply can't execute `apt-get install unzip` as that doesn't work on OSX. On OSX you'd need to use _homebrew_ (http://brew.sh/):

Now, I'm wondering what you wanna do:
- Add documentations so people need to manually install it themselves before using any library like bau that requires on scriptcs?
- Create an prerequisites.sh (or anything like that) that checks whether everything is installed and optionally installs it for you?

Cheers

**Comment by adamralph** [comment]
Interesting information, thanks! I thought I tested bau.sh on my girlfriend's Mac but perhaps not :wink:.

Ultimately all that stuff in bau.sh is just a workaround for not having an easy install story for scriptcs on OSX and Linux, but that is changing with SVM - https://github.com/paulbouwer/scriptcs-svm. I think in the meantime some documentation will be enough. The .travis.yml file can still do the funky download and unzip to get things building over there but bau.sh can boil down to something as simple as https://github.com/bau-build/bau/blob/dev/bau.bat.

**Comment by eatdrinksleepcode** [comment]
What is the status of this? I am trying to get started on a Mac and I'm not sure how or if I can do a build.

**Comment by eatdrinksleepcode** [comment]
For reference I was able to complete a successful build by changing the current wget line in bau.sh to

```
curl -L -o ScriptCs.0.13.3.nupkg "https://chocolatey.org/api/v2/package/ScriptCs/0.13.3/"
```

Apparently I already had unzip installed.

**Comment by adamralph** [comment]
Now that scriptcs has a reasonable installation path on both Mac and OSX, I think we can just get rid of this scriptcs.exe bootstrapping altogether from bau.sh and change the build instructions to state that scriptcs should be installed as a pre-requisite.

scriptcs can be installed on Mac via homebrew or on both Mac or Linux via svm (https://github.com/scriptcs-contrib/svm/wiki/Installing-svm).

**Comment by adamralph** [comment]
@cH40z-Lord @eatdrinksleepcode please see the latest build instructions https://github.com/bau-build/bau/blob/dev/how_to_build.md

**Comment by keichinger** [comment]
@adamralph looks good! Thanks for taking care of it.
