### ISSUE TITLE
Unify Windows and Mono builds for Bau

### ISSUE THREAD

**Issue by eatdrinksleepcode** [adamralph/bau#202]
Bau currently uses two different build files for .NET versus Mono. It would be good to unify them such that both environments have access to the full range of build tasks (e.g. "accept").

Since Bau is dogfooding itself, this issue will likely spill over into the more general question of how Bau supports building in Mono environments. However, for tracking purposes, this issue is specifically about unifying the Bau build files.

**Comment by adamralph** [comment]
Agreed. There are two reasons a separate file exists:
1. Differences in language support in scriptcs, between the Roslyn engine and Mono engine
2. Lack of a x-plat build task (i.e. MSBuild and XBuild)

Point 1) has been alleviated somewhat in later versions of scriptcs so perhaps things can already be more closely aligned in that respect.

Point 2) requires an extension to Bau.MSBuild, which I think should auto-detect and switch between MSBuild and XBuild appropriately. The name Bau.MSBuild perhaps isn't ideal, although ultimately it's purpose is to execute MSBuild files, regardless of platform, so it kind of makes sense.

**Comment by eatdrinksleepcode** [comment]
That brings up an interesting question (which may evolve into its own issue): how should indvidual tasks handle cross-platform execution? There are two obvious answers:

1) Change the runtime used. This is what the Xunit task currently does: when running on Mono, it invokes the Xunit executable using Mono.

2) Change the tool that is executed. This is what you are suggesting for the MSBuild task: run XBuild when MSBuild is not available. The question then becomes, how do we know when MSBuild is not available? Is it purely based on platform detection? What happens when MSBuild becomes available for other platforms? Also, are there times when another tool is available (like XBuild), but the user might want to instead invoke the original tool using a different runtime (e.g. Mono)?

Should the answer be the same for all tasks, or does it make sense to handle this on a task-by-task basis? Also, are there times when we can't reasonably be certain ahead of time which choice is correct, and so we choose to surface the decision to user in the API of the task?
