### ISSUE TITLE
Write Documentation

### ISSUE THREAD

**Issue by cthulhusec** [adamralph/bau#30]
- [x] CONTRIBUTING.md
- [x] How to Build
- [x] Quickstart
- [x] Samples

---
### Update (@adamralph)

In addition to these items, the [wiki](https://github.com/bau-build/bau/wiki) has a few more pages now and the [readme](https://github.com/bau-build/bau) has been updated.
- https://github.com/bau-build/bau/blob/dev/CONTRIBUTING.md
- https://github.com/bau-build/bau/blob/dev/how_to_build.md
- https://github.com/bau-build/bau/wiki/Quickstart
- https://github.com/bau-build/bau/tree/dev/src/samples

**Comment by adamralph** [comment]
:thumbsup:

**Comment by adamralph** [comment]
@buddytex all done!

Thanks for raising this issue and prompting me into doing it :blush:

**Comment by adamralph** [comment]
@buddytex do you have a twitter handle? I'd like to give you some public credit! :wink:

**Comment by cthulhusec** [comment]
Yes I do, @Buddytex :smile:
