### ISSUE TITLE
xunit.net plugin

### ISSUE THREAD

**Issue by adamralph** [adamralph/bau#36]

**Comment by adamralph** [comment]
Needs to use `mono` as the command in Mono.

**Comment by adamralph** [comment]
Casing saga is in full flow http://adamralph.com/2015/03/04/nuget-gallery-casing-woes/

**Comment by adamralph** [comment]
See https://github.com/NuGet/NuGetGallery/issues/2379

**Comment by aarondandy** [comment]
For now I am working around this by:
1. Remove `Bau.Xunit` (or `Bau.XUnit`) from `scriptcs_packages.config`
2. Kill the `scriptcs_packages` folder if it is messed up
3. Edit your build script (`.csx`) file to use `.Exec("xunit")` instead of `Xunit` and use the `Run` option for the path to the xunit runner and `With` for all the assembly paths to test.

Alternatively, just take tests out :disappointed:

**Comment by adamralph** [comment]
@aarondandy see this comment https://github.com/scriptcs/scriptcs/issues/952#issuecomment-77467713

I've uploaded a Bau.Xunit.Temp package which you can switch to for now.

**Comment by adamralph** [comment]
BTW - please help spread the word :wink:

**Comment by aarondandy** [comment]
Haha, the reason I made that comment was for @robertd

**Comment by robertd** [comment]
lol

**Comment by robertd** [comment]
Is there a Nuget issue for this bug? Since `NuGet.CommandLine` is failing too... :smile: 

edit: nvm ... I saw @adamralph's comment above

**Comment by aarondandy** [comment]
I think that is a scriptcs issue, if it fails on Xunit it seems to fail on any others that would come after it.

**Comment by adamralph** [comment]
@robertd yes, it's purely a NuGet gallery issue. It's not a problem in scriptcs or NuGet.CommandLine.

Here it is: https://github.com/NuGet/NuGetGallery/issues/2379

@aarondandy you're correct that scriptcs fails on subsequent packages, but it's really a moot point since if one package is missing your almost always going to be screwed anyway. The log messages are bit confusing from scriptcs and I've raised this issue to cover that https://github.com/scriptcs/scriptcs/issues/952

**Comment by adamralph** [comment]
@robertd you should be able to use Bau.Xunit again from version 0.1.0-beta08 onwards - https://www.nuget.org/packages/Bau.Xunit/0.1.0-beta08

For anyone who wants to retweet - https://twitter.com/baubuild/status/578667877206745088
