### ISSUE TITLE
Task descriptions and command line switch to display

### ISSUE THREAD

**Issue by adamralph** [adamralph/bau#65]
``` C#
Task("default").Does("Executes default tasks").Do(...
```

`scriptcs baufile.csx -- -D`

```
default
    Executes default tasks
```

**Comment by aarondandy** [comment]
I will be taking this on as part of #166

Added in https://github.com/aarondandy/bau/commit/3eb204add67fdbc766f2314bf05cb5afa326289b and acceptance tests will be written as part of the other issue as description is a core part of it.

**Comment by adamralph** [comment]
This has gone out in https://www.nuget.org/packages/Bau/0.1.0-beta09
